apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  serviceName: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 7474:7474 /data /logs"]
        securityContext:
          runAsUser: 0  # Run as root to modify ownership
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
          
      containers:
      - name: neo4j
        image: neo4j
        resources:
          limits:
            memory: "4Gi"
            cpu: "200m"
          requests:
            memory: "600Mi"
            cpu: "100m"
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password123"  # Set Neo4j username and password
        - name: NEO4J_dbms_memory_heap_initial__size
          value: "512M"
        - name: NEO4J_dbms_memory_heap_max__size
          value: "2G"
        - name: NEO4J_dbms_memory_pagecache_size
          value: "512M"
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        - name: NEO4J_dbms_default__listen__address
          value: "0.0.0.0"
        ports:
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: neo4j-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  clusterIP: None
  selector:
    app: neo4j
  ports:
  - port: 7687
    targetPort: 7687
    name: bolt
