apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: lokesh2yss/linkedin-app-notification-service
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: k8s
         - name: DB_USER
           value: "postgres"
         - name: DB_PASSWORD
           value: "Postgres@123"
         - name: DB_NAME
           value: "microserviceNotificationDB"
         - name: DB_SERVICE
           value: "notification-db"
        ports:
        - containerPort: 9040

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 9040


