apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-db
spec:
  selector:
    matchLabels:
      app: notification-db
  serviceName: notification-db
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
      - name: notification-db
        image: postgres:16
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "Postgres@123"
          - name: POSTGRES_DB
            value: "microserviceNotificationDB"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard-rwo"
      volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  name: notification-db
spec:
  clusterIP: None
  selector:
    app: notification-db
  ports:
  - port: 5432
    targetPort: 5432

