apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: lokesh2yss/linkedin-app-user-service
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: k8s
         - name: DB_USER
           value: "postgres"
         - name: DB_PASSWORD
           value: "Postgres@123"
         - name: DB_NAME
           value: "microserviceUserDB"
         - name: DB_SERVICE
           value: "user-db"
        ports:
        - containerPort: 9020

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 9020


